package tech.illuin.wombat.persistence.backend.postgres;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import tech.illuin.wombat.persistence.dialect.JsonPathDialect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises the postgresql baseline migration against a real server. Beyond "the DDL parses", the
 * points worth guarding are the ones where the SQLite definitions could not be carried over
 * verbatim: integer widths, the REAL/DOUBLE PRECISION difference, timestamp storage, the identity
 * column standing in for a rowid alias, and the json expression indexes replacing json_extract.
 */
class PostgresSchemaTest
{
    private static final Set<String> EXPECTED_TABLES = Set.of(
        "server_metrics", "model_metrics", "environments", "assets", "asset_config_history"
    );

    private static String jdbcUrl;

    @BeforeAll
    static void migrateBaseline() throws SQLException
    {
        jdbcUrl = PostgresTestContainer.freshDatabase("wombat_schema");
        flyway(jdbcUrl).migrate();
    }

    @Test
    void migrate_createsExactlyTheTablesTheAppMaps() throws SQLException
    {
        assertEquals(EXPECTED_TABLES, postgresTables());
    }

    @Test
    void migrate_isIdempotent()
    {
        MigrateResult result = flyway(jdbcUrl).migrate();
        assertEquals(0, result.migrationsExecuted);
    }

    @Test
    void serverMetrics_columnsMatchTheEntityFieldWidths() throws SQLException
    {
        Map<String, String> types = postgresColumnTypes("server_metrics");

        assertEquals("bigint", types.get("id"));
        // Epoch millis overflow the 32-bit INTEGER the SQLite column definition names.
        assertEquals("bigint", types.get("instant_ms"));
        assertEquals("text", types.get("data"));
        // SQLite REAL is 64-bit and maps to double fields; Postgres REAL would only be 32-bit.
        assertEquals("double precision", types.get("cpu_nanocores"));
        assertEquals("double precision", types.get("ram_bytes"));
    }

    @Test
    void modelMetrics_storesTokenCountsAsBigint() throws SQLException
    {
        Map<String, String> types = postgresColumnTypes("model_metrics");

        assertEquals("bigint", types.get("instant_ms"));
        assertEquals("bigint", types.get("output_tokens"));
    }

    @Test
    void auditTimestamps_areRealTimestampsNotEpochMillis() throws SQLException
    {
        assertEquals("timestamp with time zone", postgresColumnTypes("environments").get("created_at"));
        assertEquals("timestamp with time zone", postgresColumnTypes("environments").get("disabled_at"));
        assertEquals("timestamp with time zone", postgresColumnTypes("assets").get("deleted_at"));
        assertEquals("timestamp with time zone", postgresColumnTypes("asset_config_history").get("changed_at"));
    }

    @Test
    void identityId_isAssignedAutomaticallyAndStillAcceptsAnExplicitValue() throws SQLException
    {
        try (Connection conn = PostgresTestContainer.connect(jdbcUrl))
        {
            long generated = insertMetricReturningId(conn, null);
            assertNotEquals(0L, generated);

            // GENERATED BY DEFAULT (rather than ALWAYS) keeps a SQLite dump importable with its ids.
            long explicit = insertMetricReturningId(conn, 4242L);
            assertEquals(4242L, explicit);

            try (Statement stmt = conn.createStatement())
            {
                stmt.executeUpdate("DELETE FROM server_metrics");
            }
        }
    }

    @Test
    void assets_rejectAnEnvironmentThatDoesNotExist() throws SQLException
    {
        try (Connection conn = PostgresTestContainer.connect(jdbcUrl);
             Statement stmt = conn.createStatement())
        {
            SQLException error = assertThrows(SQLException.class, () -> stmt.executeUpdate(
                "INSERT INTO assets (id, environment_id, name, type, properties, created_at, updated_at)"
                + " VALUES ('a1', 'no-such-env', 'Asset', 'KUBERNETES_API', '{}', now(), now())"));

            assertTrue(error.getMessage().contains("assets_environment_id_fkey"), error.getMessage());
        }
    }

    @Test
    void uuidIndex_allowsSeveralNullsButRejectsDuplicates() throws SQLException
    {
        try (Connection conn = PostgresTestContainer.connect(jdbcUrl);
             Statement stmt = conn.createStatement())
        {
            // The SQLite schema leaves uuid nullable, so the unique index must tolerate repeated NULLs.
            stmt.executeUpdate(insertEnvironment("env-null-a", null));
            stmt.executeUpdate(insertEnvironment("env-null-b", null));
            stmt.executeUpdate(insertEnvironment("env-dup-a", "shared-uuid"));

            SQLException error = assertThrows(SQLException.class,
                () -> stmt.executeUpdate(insertEnvironment("env-dup-b", "shared-uuid")));
            assertTrue(error.getMessage().contains("idx_environments_uuid"), error.getMessage());

            stmt.executeUpdate("DELETE FROM environments");
        }
    }

    @Test
    void jsonExpressionIndexes_areUsableByThePlanner() throws SQLException
    {
        try (Connection conn = PostgresTestContainer.connect(jdbcUrl);
             Statement stmt = conn.createStatement())
        {
            // Without this the planner would prefer a sequential scan on an empty table and the
            // assertion would say nothing about whether the index is usable at all.
            stmt.execute("SET enable_seqscan = off");

            String metricsPlan = explain(stmt, "SELECT id FROM server_metrics WHERE "
                + JsonPathDialect.POSTGRESQL.text("data", "cluster") + " = 'c1' AND instant_ms >= 0");
            assertTrue(metricsPlan.contains("idx_server_metrics_cluster_instant"), metricsPlan);

            String modelPlan = explain(stmt, "SELECT id FROM model_metrics WHERE "
                + JsonPathDialect.POSTGRESQL.text("data", "assetId") + " = 'a1' AND instant_ms >= 0");
            assertTrue(modelPlan.contains("idx_model_metrics_asset_instant"), modelPlan);
        }
    }

    private static Flyway flyway(String url)
    {
        return Flyway.configure()
            .dataSource(url, PostgresTestContainer.username(), PostgresTestContainer.password())
            .locations("classpath:db/migration/postgresql")
            .load();
    }

    private static long insertMetricReturningId(Connection conn, Long id) throws SQLException
    {
        String columns = id == null ? "" : "id, ";
        String values = id == null ? "" : id + ", ";
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(
                 "INSERT INTO server_metrics (" + columns + "instant_ms, data, cpu_nanocores, ram_bytes)"
                 + " VALUES (" + values + "1000, '{\"cluster\":\"c1\"}', 1, 1) RETURNING id"))
        {
            rs.next();
            return rs.getLong(1);
        }
    }

    private static String insertEnvironment(String id, String uuid)
    {
        String uuidValue = uuid == null ? "NULL" : "'" + uuid + "'";
        return "INSERT INTO environments (id, name, created_at, updated_at, uuid)"
            + " VALUES ('" + id + "', 'Env', now(), now(), " + uuidValue + ")";
    }

    private static String explain(Statement stmt, String query) throws SQLException
    {
        StringBuilder plan = new StringBuilder();
        try (ResultSet rs = stmt.executeQuery("EXPLAIN (COSTS OFF) " + query))
        {
            while (rs.next())
                plan.append(rs.getString(1)).append('\n');
        }
        return plan.toString();
    }

    private static Set<String> postgresTables() throws SQLException
    {
        Set<String> tables = new TreeSet<>();
        try (Connection conn = PostgresTestContainer.connect(jdbcUrl);
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(
                 "SELECT table_name FROM information_schema.tables"
                 + " WHERE table_schema = 'public' AND table_type = 'BASE TABLE'"))
        {
            while (rs.next())
                addUnlessFlywayHistory(tables, rs.getString(1));
        }
        return tables;
    }

    private static Map<String, String> postgresColumnTypes(String table) throws SQLException
    {
        Map<String, String> types = new LinkedHashMap<>();
        try (Connection conn = PostgresTestContainer.connect(jdbcUrl);
             PreparedStatement stmt = conn.prepareStatement(
                 "SELECT column_name, data_type FROM information_schema.columns"
                 + " WHERE table_schema = 'public' AND table_name = ? ORDER BY ordinal_position"))
        {
            stmt.setString(1, table);
            try (ResultSet rs = stmt.executeQuery())
            {
                while (rs.next())
                    types.put(rs.getString(1), rs.getString(2));
            }
        }
        return types;
    }




    private static void addUnlessFlywayHistory(Set<String> tables, String name)
    {
        if (!"flyway_schema_history".equals(name))
            tables.add(name);
    }
}
