-- Baseline PostgreSQL schema. This single migration produces the exact same final state as the
-- SQLite chain V1..V10 (db/migration/sqlite) — the intermediate steps only exist there to migrate
-- pre-existing local databases in place; a Postgres deployment starts empty, so it is created
-- once, in its final shape. The tables are seeded/reconciled by the app at startup from the
-- monitored-environments YAML.
--
-- Type mapping applied against the SQLite definitions:
--   * `id INTEGER PRIMARY KEY` (an implicit SQLite rowid alias, i.e. auto-assigned) becomes a
--     `BIGINT` identity column, matching @GeneratedValue(strategy = IDENTITY) on the entities.
--     BY DEFAULT (rather than ALWAYS) keeps explicit ids insertable so a SQLite dump can be
--     imported without stripping the id column.
--   * `instantMs` / `outputTokens` are epoch millis and token counts, so 64-bit `BIGINT`, not the
--     32-bit `INTEGER` the name suggests. Both are written unquoted, hence folded to lowercase by
--     Postgres — which is what the unquoted `instantMs` / `outputTokens` references emitted by
--     Hibernate and by the native queries in KubernetesMetricRepository / LLMModelMetricRepository
--     resolve to. Do not quote them here, or those references would stop matching.
--   * `REAL` becomes `DOUBLE PRECISION`: SQLite REAL is a 64-bit float (mapped to `double` fields),
--     whereas Postgres REAL is only 32-bit.
--   * The audit timestamps carry `columnDefinition = "INTEGER"` because the SQLite JDBC driver
--     stores java.time.Instant as epoch millis. Postgres has a real timestamp type and Hibernate
--     binds Instant as TIMESTAMP_UTC there, so they become `TIMESTAMP WITH TIME ZONE`.
--   * The self-describing `data` payloads stay `TEXT`: they are (de)serialized by
--     MetricDataConverter / AssetDataConverter as plain JSON strings, and a `jsonb` column would
--     reject those varchar-typed bind parameters. Only the indexes below cast to jsonb.

-- Per-container CPU/RAM samples. The source labels (type, cluster, namespace, pod, container) live
-- in the self-describing JSON `data` column so non-Kubernetes sources fit the same table.
CREATE TABLE server_metrics (
    id            BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instantMs     BIGINT           NOT NULL,
    data          TEXT             NOT NULL,
    cpu_nanocores DOUBLE PRECISION NOT NULL,
    ram_bytes     DOUBLE PRECISION NOT NULL
);

-- SQLite indexes `json_extract(data, '$.cluster')`; the Postgres equivalent extracts through jsonb.
-- Both the cast and `->>` are immutable, so the expression is indexable.
CREATE INDEX idx_server_metrics_cluster_instant ON server_metrics ((data::jsonb ->> 'cluster'), instantMs);

-- LLM output-token usage sampled from Prometheus. Each row holds the tokens produced since the
-- previous aggregation (a per-tick delta); summing rows over a range yields total output tokens.
CREATE TABLE model_metrics (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instantMs    BIGINT NOT NULL,
    data         TEXT   NOT NULL,
    outputTokens BIGINT NOT NULL
);

CREATE INDEX idx_model_metrics_profile_instant ON model_metrics ((data::jsonb ->> 'profileId'), instantMs);

-- Environments act as an activity registry: the app only uses environments whose disabled_at is
-- NULL. Rows are seeded at startup from the monitored-environments config, which stays the source
-- of truth for asset definitions.
CREATE TABLE environments (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    disabled_at TIMESTAMP WITH TIME ZONE,
    uuid        TEXT
);

CREATE UNIQUE INDEX idx_environments_uuid ON environments (uuid);

-- Assets are self-contained: only the fields shared by every asset kind are dedicated columns, and
-- the type-specific payload (KUBERNETES_API: config_path/namespace/context/read_timeout,
-- LLM_STATIC / LLM_PROMETHEUS: their own keys) plus the inlined impact `profile` live in the
-- self-describing JSON `data` column, whose `type` discriminator mirrors the type column.
-- deleted_at is a soft delete, mirroring environments.disabled_at.
CREATE TABLE assets (
    id             TEXT PRIMARY KEY,
    environment_id TEXT NOT NULL REFERENCES environments (id),
    name           TEXT NOT NULL,
    type           TEXT NOT NULL,
    data           TEXT NOT NULL,
    uuid           TEXT,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at     TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_assets_environment ON assets (environment_id);
CREATE UNIQUE INDEX idx_assets_uuid ON assets (uuid);

-- Append-only audit trail of asset config changes. asset_id is intentionally NOT a foreign key:
-- history must survive asset deletion.
CREATE TABLE asset_config_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id       TEXT NOT NULL,
    environment_id TEXT NOT NULL,
    action         TEXT NOT NULL,
    changed_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    snapshot       TEXT NOT NULL
);

CREATE INDEX idx_asset_config_history_asset ON asset_config_history (asset_id, changed_at);
